# Publish docker image on release
# TODO:
#   - Later add versioning of docker images by release version
#   - Update the docker labels

name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: feltlabs/llm-compute:latest
          labels: |
            ai.feltlabs.version=${{ github.ref_name }}
            ai.feltlabs.name=llm-compute
            ai.feltlabs.description=Docker image for fine-tuning LLMs with FELT Labs. Provides support for GPU training.
            ai.feltlabs.url=https://feltlabs.ai
            ai.feltlabs.build-date=${{ github.event.workflow_run.created_at }}
